### ISSUE TITLE
sepolicy: address denials

### ISSUE THREAD

**Issue by Parixshit** [Deepak5310/android_device_realme_RMX1921#1]
01-31 13:20:26.955  1066  3180 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (1441155)
01-31 13:20:27.001  3146  3146 W eparts.settings: type=1400 audit(0.0:355): avc: denied { read } for name="vmax_mv_user" dev="sysfs" ino=52031 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_leds:s0 tclass=file permissive=0
01-31 13:20:27.005  3146  3146 W eparts.settings: type=1400 audit(0.0:356): avc: denied { read } for name="vmax_mv_strong" dev="sysfs" ino=52032 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_leds:s0 tclass=file permissive=0
01-31 13:20:27.005  3146  3146 W eparts.settings: type=1400 audit(0.0:357): avc: denied { read } for name="vmax_mv_call" dev="sysfs" ino=52033 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_leds:s0 tclass=file permissive=0
01-31 13:20:27.009  3146  3146 W eparts.settings: type=1400 audit(0.0:358): avc: denied { write } for name="vmax_override" dev="sysfs" ino=52030 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_leds:s0 tclass=file permissive=0
01-31 13:20:27.009  3146  3146 W eparts.settings: type=1400 audit(0.0:359): avc: denied { write } for name="vmax_override" dev="sysfs" ino=52030 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_leds:s0 tclass=file permissive=0
01-31 13:20:27.158  1066  1720 I EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_FINISHED
01-31 13:20:27.160   952   952 I android.hardware.power-service-qti: Power setMode: 5 to: 0
01-31 13:20:27.171  1066  1717 I ActivityTaskManager: Displayed com.realmeparts.settings/.RealmePartsActivity: +236ms

**Comment by Deepak5310** [comment]
allow system_app sysfs_leds:file { read  write };
